version: "3.9"

services:
  frontendrbac:
    container_name: frontend-rbac
    build: .
    image: frontend-rbac:1.0.0
    ports:
      - "3666:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=https://api-rbac.tokocoding.com/api
    env_file:
      - .env
    networks:
      - rabc_doni_network
    restart: unless-stopped

networks:
  rabc_doni_network:
    driver: bridge
    name: rabc_doni_network